### ISSUE TITLE
Move docs over to github

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#28]
Assuming Floodgap give us permission. Move the docs over to her under github-pages (or Wiki, but likely easier under Github pages).

**Comment by funnelfiasco** [comment]
We might want to rewrite them in markdown or something source-y and then we can publish as various HTML/PDF sections.

**Comment by edison23** [comment]
shall we keep the same structure? bcs it seemed to me a bit unclear sometimes, but on the other hand.. who wants to rewrite and reread it all, i admit

**Comment by funnelfiasco** [comment]
I'm inclined to go for a rewrite. Cameron's docs, while thorough, were hard
to follow. I've done a fair amount of documentation, so I'm happy to do the
initial work and let the community smooth things out.

**Comment by funnelfiasco** [comment]
Okay, I've thought about this and here's my plan for the docs. I'll wait a couple of days before moving on this in case there are objections and discussions.
- I'll create a separate repo for the docs to minimize what people grab if they just want the core oysttyer
- I'll write them in ReST/Sphinx so we can publish them on readthedocs.org. They'll also render happily in the GitHub browser view, so it's a nice compromise.
- I'll license them CC-BY-SA
- I'll.... uh, yeah, that's probably it for now.

Using Sphinx makes me a little sad because I don't particularly like it, but I do like publishing the docs to Read the Docs. This would make some of the denser docs easier to consume, while still allowing the "here's how you get started with OysTTYer" doc nice and small.

**Comment by atomicules** [comment]
Well, like I said, I was planning (and had just about made a start) 
on moving the existing docs across to the Wiki and converting to 
markdown format in the meantime. But if you are will to take on a 
whole re-write I'd be really grateful for that and I could focus on 
the code instead.

**Comment by funnelfiasco** [comment]
If you want to, we can create the docs repo now and you can toss the markdown that you've converted into there, and as I rewrite stuff, we can start dropping the old markdown.

**Comment by atomicules** [comment]
Sure, go for it. I'll need to switch computers to get the pandoc 
conversion, etc.

**Comment by funnelfiasco** [comment]
I changed my mind a bit after looking into GitHub pages more. I think that makes more sense for us. At any rate, I've started the User Guide: http://oysttyer.github.io/docs/userGuide.html

More to come in the next few days. In the meantime, documentation bugs should be filed as issues on https://github.com/oysttyer/oysttyer.github.io
