### ISSUE TITLE
Get tweet by name and long ID

### ISSUE THREAD

**Issue by perception101** [oysttyer/oysttyer#72]
For various reasons, I sometimes see tweets linked in an IRC channel with the full URL, for example,

`https://twitter.com/username/status/897364987698576398452345`

I'd like to be able to refer to that tweet in oysttyer, but sometimes `/again username` doesn't go far enough back and even if it does, it's not obvious which tweet is being referred to.

So, I'd like to be able to do `/again username 897364987698576398452345` to see the specific tweet (or some other command).

**Comment by atomicules** [comment]
Forgot to comment originally, but you can already (since the TTYtter days) operate on tweet IDs, e.g:

```
/dump 897364987698576398452345
/th 897364987698576398452345
/rt 897364987698576398452345
```

So, it depends exactly what you want to do with the tweet, but you might already have the functionality you need. Thread is probably your best bet.

However, we could also think about adding an explicit command to get a single tweet.

**Comment by perception101** [comment]
Aha, perfect, the documentation doesn't seem to reflect that unless I missed something?  Either way - this can be closed!  Thanks.

**Comment by atomicules** [comment]
I'm sure the original TTYtter docs mention this functionality. We 
still have ways to go on sorting out our documentation out though.
