### ISSUE TITLE
Possible to write out to a file? 

### ISSUE THREAD

**Issue by kabads** [oysttyer/oysttyer#82]
I'm interested in capturing a timeframe of tweets in a feed in to a file (which could later be emailed). Will oysttyer do something like this?

**Comment by funnelfiasco** [comment]
The simplest way is to redirect stdout (but that makes it a little hard to use): `oysttyer > outputfile.txt`

Arguably the best way would be to write a plugin that dumps incoming tweets to a database, which you could later query. I've thought about doing that in order to make Twitter-based giveaways easier to implement, but I've never actually done it.

**Comment by werid** [comment]
I haven't used it in awhile, so not sure if it works as-is with the current oysttyer code, but someone wrote this 5 years ago. 

https://github.com/pr4wn/ttytter-exts/tree/master/pwntter

**Comment by kabads** [comment]
Thanks - I'll check this out. Unfortunately though, I'm not familiar enough with perl to write a plugin.
