### ISSUE TITLE
Some videos display as m3u8 when in a quoted tweet

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#93]
As Twitter is making changes with the links, I guess this is related to #92 and #86.
When a tweet quoting [this tweet](https://twitter.com/BryFun1/status/785310574917804032) appeared in my timeline, the video link in the quoted tweet was m3u8 instead of mp4. When doing /th 785310574917804032 the link was correct, this seems to only happen when it is quoted naturally in your timeline and cannot be reproduced otherwise. This is using 2.8.0 (2a1600162285aaaf465f92ea1fe6533a86da0837).

**Comment by funnelfiasco** [comment]
Ah, I see what's going on here. It looks like the video includes several variants. I suspect it's one of two things:
1. we just go with the first or last match of `content_type` and the ordering in the JSON isn't always the same when we get it via the streaming API and when we get it via the REST API (which is what, e.g., the `/thread` command uses)
2. The way we handle quoted tweets doesn't include all of the variants.

I'm much more inclined to say it's the first one, since I think the 2nd one might require that to be an explicit decision, which we don't make. I'll try to dig into it a little bit more.

**Comment by funnelfiasco** [comment]
I just pushed a commit that will take mp4 URLs first and use m3u8 if there's no mp4. If nothing else, it should be predictable now. I think preferring mp4 to m3u8 is the right decision because more clients seem to accept mp4. I'm leaving this issue open a bit to
1. Give @Azenet the opportunity to say "no, you completely missed my point"
2. Let someone else chime in to let me know why I made the wrong decision.

**Comment by atomicules** [comment]
You might as well just roll back this change: https://github.com/oysttyer/oysttyer/commit/ba40712f1deca14df7e6e2abcda7e6579e2d1b5c

**Comment by funnelfiasco** [comment]
I don't want to roll back ba40712 because I expect Twitter will yank the rug out from us at some point, so it's good having m3u8 fallback.

**Comment by funnelfiasco** [comment]
Okay, seems to be working, so I've pushed 2.8.1 and I'm closing this issue.
