### ISSUE TITLE
Wrong message when liking a retweeted status from another user

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#98]
Hi,

Apparently the message [here](https://github.com/oysttyer/oysttyer/blob/f870db90d005d8965220ca63c9e36f6336ab76a7/oysttyer.pl#L5804) is invalid if you like a tweet that was retweeted in your timeline, even though I think I never seen that happen before. Maybe the "favorited_retweet" event is dispatched in cases in which it wasn't before.

Example:
```
a0> <%userB> RT @userA: some tweet
/like a0
>>> @you just liked @userA's tweet: "some tweet"
>>> @you just liked a tweet you retweeted: "RT @userA: some tweet"
-- like created for tweet id "#12345": "RT @userA: some tweet"
```

**Comment by funnelfiasco** [comment]
I was thinking that it was probably me misunderstanding what that event is, but no, it gets send under at least two cases:
1. Someone likes a tweet you retweeted
2. You like a tweet retweeted into your timeline

Seems like those should be separate events, but I guess Twitter thinks otherwise. Anyway, it should be pretty trivial to suppress the message in the second case. I'll test it for a bit and push if it makes me happy.
